source "https://rubygems.org"

ruby "~> 3.3.0"

gem "fastlane", "2.219.0"
gem "abbrev", "0.1.1"

plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)